# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:

# Всё отличие – заменяем build на image и указываем, какой образ использовать
services:
  django_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: diablo8520456/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: diablo8520456/taski_frontend  # Качаем с DockerHub
    env_file: .env
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: diablo8520456/taski_gateway  # Качаем с DockerHub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80

